on:
  pull_request:
    paths-ignore:
      - "*.md"
      - ".txt"

  push:
    paths-ignore:
      - "*.md"
      - ".txt"
    branches:
      - master

jobs:

  build:
    name: "Build and test"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: "1.12"

      - uses: actions/checkout@v1

      - name: "build source workspace"
        run: "make workspace"

      - name: "golang pkg cache"
        uses: "actions/cache@v1"
        with:
          path: "~/go/pkg"
          key: "pkg-${{hashFiles('go.mod')}}"

      - name: "lint and test"
        run: "make check"

      - name: "build"
        run: "make build"
